### ISSUE TITLE
Merging JDK versions code

### ISSUE THREAD

**Issue by jankratochvil** [adinn/unwinder#1]
I have ported it to [arm32](https://github.com/jankratochvil/adinn-unwinder/tree/zulu-aarch32) and [i686](https://github.com/jankratochvil/adinn-unwinder/tree/i686). Sure I plan to merge it into a single codebase detecting the arch from a single file / single branch. I would also like to merge it to your repository.

But first I think it would be obviously best to merge `dbg.py`, `dbg7.py `and `dbg8.py` into a runtime detection (either by available symbols or one can always also read `JDK_Version::_current._major`) for `dbg8.py` done as #2. Otherwise all the branches become a nightmare to maintain. Personally (=company Azul) I think I am not interested in `dbg7.py` but I guess you still would like me to merge it including `dbg7.py` (which is sure fine) - should I?

**Comment by adinn** [comment]
Hi Jan. Sorry for the delay in responding -- I only just got back from PTO today.

Thanks very much for looking into this code and more so for submitting a PR to improve it. I am afraid I have not been actively maintaining it due to lack of available time. Are you hoping to continue adding to the current code or is this just a one off patch? If you are willing and able to help with maintenance then I'm very happy to collaborate as far as time allows. That doesn't really require a master release to exist in my repo but I would be happy to use it as a target for other PRs if you would prefer.

> But first I think it would be obviously best to merge dbg.py, dbg7.py and dbg8.py into a runtime detection

Yes, I am happy with this idea -- the parts of the JVM this code depends on have changed between releases but not greatly. So, a single version that uses runtime detection seems like a workable idea. I also agree that the jdk7 code is best left unmerged. jdk7u support is not enough of a priority for it to be worth complicating the code in the merged version and also the existing code is unlikely to need an maintenance so can just stay as is as a special case. Obviously jdk8u and jdk11u support is the current priority. The code in dbg.py was developed on jdk9 but I believe it still works fine for jdk11u. I am happy to pull your PR so we have one version for those two releases

It would be nice also to support later releases. I am not sure the current code works correctly on jdk17u -- I cannot recall specific changes that might lead to breakage but I have an idea that there have been some CDS-related changes that could be a problem. It would be good to get it to work on that release too as jdk17u deployments are steadily becoming more common. I guess it would also be good to have a version that worked on the jdk head release. Anyway, that's for a later update.

n.b. I appreciate that you have commented all the places where jdk release-specific behaviour is implemented. That approach can probably just be extended to deal with changes needed for later releases -- or alternatively a big enough change might imply the need for release-specific variants of some of the python functions/methods. Also an issue for a later update.

**Comment by jankratochvil** [comment]
I may implement some more archs for the unwinding. But sure it is only a very minor project for me in my job. Yes, I would prefer to keep the repository in your github so far.
I was asking in our company and there isn't much interest in JDK <=7 for this unwinding project so I am keeping `dbg7.py` intact.
Thanks for reminding me to test recent versions of JDK, I have tested now `jdk17u` and a smoke test does work for me.
I think my questions of this issue have been answered so I am closing it, thanks.

**Comment by adinn** [comment]
Thanks for the contributions and also for checking jdk17u.
